version: '3'
services:
    web:
        container_name: php-apache
        build:
            context: ./
            dockerfile: PHP.Dockerfile
        volumes:
            - ../src:/var/www/html/
        ports:
            - 8000:80
        links: 
            - db
    db:
        container_name: db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todolist
            MYSQL_USER: admin
            MYSQL_PASSWORD: test
        ports:
            - 9906:9906
        volumes:
            - data:/var/www/mysql/
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
        links: 
            - db
volumes:
    data:


